jwt:
  secret: ${JWT_SECRET}
spring:
  jackson:
    # Date format string or a fully-qualified date format class name. For instance, 'yyyy-MM-dd HH:mm:ss'
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${USERPASSWORD}


  jpa:
    defer-datasource-initialization: true
    hibernate:
        #ddl-auro: update
        ddl-auto: create
        connection:
          charSet: UTF-8 # ??? ??

    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:/db/data.sql

#  mail:
#    default-encoding: UTF-8
#    host: smtp.gmail.com
#    port: 587
#    username: [gyun1712@gmail.com] #<자기 구글 E-mail주소>
#    password: [jfnh jemp eies pdpj] #<구글 비밀번호=>앱 비밀번호로 변경>
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    protocol: smtp

