# application-develop.yml

jwt:
  secret: ${JWT_SECRET}
spring:
  # 이메일 발송시 사용하는 html 템플릿 설정
  ## thymeleaf default settings

  thymeleaf:
    prefix: classpath:/mail-templates/   # 이메일 템플릿이 위치할 경로. classpath:를 통해 src/main/resources/ 밑으로 설정되었다.
    suffix: .html # 템플릿 파일의 확장자
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    ## thymeleaf custom settings
    cache: false

  jackson:
    # Date format string or a fully-qualified date format class name. For instance, 'yyyy-MM-dd HH:mm:ss'
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${USERPASSWORD}


  jpa:
    defer-datasource-initialization: true
    hibernate:
      #ddl-auto: create
      ddl-auto: update
        #hbm2ddl:
      # import_files: classpath:db/data.sql # DB ?? ????? ??
      #import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      connection:
        charSet: UTF-8 # ??? ??

    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:/db/data.sql